services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_db
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE=your_db
      MYSQL_USER=your_user
      MYSQL_PASSWORD=your_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
