version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: db_test
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_test
      - DB_USERNAME=root
      - DB_PASSWORD=@Andrade__g4b

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    command: npm run serve -- --port 8080 --host

volumes:
  db-data:

